# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  sync_news:
    class: SyncNewsJob
    queue: default
    schedule: every minute

  sync_historical:
    class: SyncHistoricalJob
    queue: default
    schedule: every day at 9:15pm  # 1:15pm PST (UTC-8)

production:
  sync_news:
    class: SyncNewsJob
    queue: default
    schedule: every minute

  sync_historical:
    class: SyncHistoricalJob
    queue: default
    schedule: every day at 9:15pm  # 1:15pm PST (UTC-8)

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
